project_id = "tmmerifhwscgicmncndl"

[functions.articles-api]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.robots-txt]
verify_jwt = false

[functions.sync-rss-feed]
verify_jwt = false

[functions.auto-sync-feeds]
verify_jwt = false
